/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    solutions: Solution;
    news: News;
    policies: Policy;
    leads: Lead;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    solutions: SolutionsSelect<false> | SolutionsSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    policies: PoliciesSelect<false> | PoliciesSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Danh mục giải pháp/sản phẩm doanh nghiệp đang cung cấp.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions".
 */
export interface Solution {
  id: number;
  title: string;
  shortName?: string | null;
  tagline?: string | null;
  shortDesc: string;
  /**
   * Ảnh logo hiển thị trên thẻ giải pháp. Chưa upload sẽ dùng icon trụ cột tạm thời. Khuyến nghị PNG nền trong suốt.
   */
  logo?: (number | null) | Media;
  heroImage?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  features?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  pricingNote?: string | null;
  /**
   * Mỗi gói là một cột trong bảng giá / so sánh.
   */
  pricingTiers?:
    | {
        name: string;
        badge?: string | null;
        isContactForPrice?: boolean | null;
        highlight?: boolean | null;
        /**
         * Dùng để so sánh/sắp xếp. Bỏ trống nếu giá theo liên hệ.
         */
        price?: number | null;
        priceSuffix?: string | null;
        /**
         * Vd: "Từ 9.000đ/hóa đơn". Bỏ trống sẽ tự dựng từ Giá + Đơn vị.
         */
        priceLabel?: string | null;
        features?:
          | {
              text: string;
              included?: boolean | null;
              id?: string | null;
            }[]
          | null;
        ctaLabel?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Dùng cho bộ lọc và công cụ "Tìm giải pháp phù hợp".
   */
  industries?:
    | (
        | 'ban-le-thuong-mai'
        | 'f-and-b'
        | 'san-xuat'
        | 'van-tai-logistics'
        | 'giao-duc'
        | 'y-te'
        | 'tai-chinh-ngan-hang'
        | 'xay-dung-bat-dong-san'
        | 'dich-vu'
        | 'nong-nghiep'
        | 'da-nganh'
      )[]
    | null;
  needs?:
    | (
        | 'vien-thong-ket-noi'
        | 'van-phong-so'
        | 'hoa-don-ke-toan-chu-ky-so'
        | 'ban-hang-marketing'
        | 'nhan-su-bao-hiem'
        | 'cloud-ha-tang'
        | 'an-ninh-mang'
        | 'logistics-van-tai'
      )[]
    | null;
  companySizes?: ('sieu-nho' | 'nho' | 'vua' | 'lon')[] | null;
  /**
   * Gợi ý kèm theo ở trang chi tiết.
   */
  relatedSolutions?: (number | Solution)[] | null;
  /**
   * Tùy chỉnh tiêu đề/mô tả khi xuất hiện trên Google & mạng xã hội. Để trống sẽ dùng giá trị mặc định.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  pillar:
    | 'vien-thong'
    | 'chuyen-doi-so'
    | 'data-center-an-ninh-mang'
    | 'quan-tri-doanh-nghiep'
    | 'logistics-van-tai-nang-luong'
    | 'san-pham-hop-tac';
  productGroup?: ('thiet-yeu' | 'quan-tri' | 'cloud' | 'chuyen-nganh') | null;
  isFeatured?: boolean | null;
  /**
   * Số nhỏ hiển thị trước.
   */
  order?: number | null;
  /**
   * Chỉ nội dung "Đã xuất bản" mới hiển thị công khai.
   */
  status: 'draft' | 'published';
  /**
   * Để trống sẽ tự sinh từ tiêu đề. Dùng trong URL, chỉ gồm chữ thường, số và dấu gạch.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Tin tức Viettel, khuyến mãi, sự kiện, cập nhật chuyển đổi số.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  /**
   * Hiển thị ở danh sách và khi chia sẻ.
   */
  excerpt?: string | null;
  coverImage?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  relatedSolutions?: (number | Solution)[] | null;
  /**
   * Tùy chỉnh tiêu đề/mô tả khi xuất hiện trên Google & mạng xã hội. Để trống sẽ dùng giá trị mặc định.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  category: 'tin-viettel' | 'chuyen-doi-so' | 'khuyen-mai' | 'su-kien';
  publishedAt?: string | null;
  author?: string | null;
  /**
   * Chỉ nội dung "Đã xuất bản" mới hiển thị công khai.
   */
  status: 'draft' | 'published';
  /**
   * Để trống sẽ tự sinh từ tiêu đề. Dùng trong URL, chỉ gồm chữ thường, số và dấu gạch.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Nghị định, thông tư, chính sách nhà nước liên quan tới giải pháp Viettel.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "policies".
 */
export interface Policy {
  id: number;
  title: string;
  /**
   * Giải thích ngắn gọn ảnh hưởng tới doanh nghiệp.
   */
  summary: string;
  coverImage?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  attachment?: (number | null) | Media;
  /**
   * URL tới văn bản gốc trên cổng thông tin chính phủ.
   */
  sourceUrl?: string | null;
  /**
   * Vd: Nghị định hóa đơn điện tử → Sinvoice/vInvoice.
   */
  relatedSolutions?: (number | Solution)[] | null;
  /**
   * Tùy chỉnh tiêu đề/mô tả khi xuất hiện trên Google & mạng xã hội. Để trống sẽ dùng giá trị mặc định.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  documentType: 'luat' | 'nghi-dinh' | 'thong-tu' | 'quyet-dinh' | 'cong-van';
  documentNumber?: string | null;
  issuingBody?: string | null;
  effectiveDate?: string | null;
  publishedAt?: string | null;
  /**
   * Chỉ nội dung "Đã xuất bản" mới hiển thị công khai.
   */
  status: 'draft' | 'published';
  /**
   * Để trống sẽ tự sinh từ tiêu đề. Dùng trong URL, chỉ gồm chữ thường, số và dấu gạch.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Yêu cầu tư vấn/demo/báo giá gửi từ website. Quản lý & phân công xử lý tại đây.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  company?: string | null;
  phone: string;
  email?: string | null;
  type: 'tu-van' | 'demo' | 'bao-gia';
  interestedSolutions?: (number | Solution)[] | null;
  companySize?: ('sieu-nho' | 'nho' | 'vua' | 'lon') | null;
  message?: string | null;
  preferredDate?: string | null;
  timeSlot?: ('sang' | 'trua' | 'chieu' | 'toi') | null;
  consent?: boolean | null;
  leadStatus?: ('moi' | 'dang-xu-ly' | 'da-lien-he' | 'hoan-tat' | 'huy') | null;
  assignedTo?: (number | null) | User;
  source?: string | null;
  internalNotes?:
    | {
        note: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Editor: quản lý giải pháp/tin tức/chính sách. Sales: quản lý lead. Admin: toàn quyền.
   */
  roles: ('admin' | 'editor' | 'sales')[];
  phone?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'solutions';
        value: number | Solution;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'policies';
        value: number | Policy;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions_select".
 */
export interface SolutionsSelect<T extends boolean = true> {
  title?: T;
  shortName?: T;
  tagline?: T;
  shortDesc?: T;
  logo?: T;
  heroImage?: T;
  body?: T;
  features?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  pricingNote?: T;
  pricingTiers?:
    | T
    | {
        name?: T;
        badge?: T;
        isContactForPrice?: T;
        highlight?: T;
        price?: T;
        priceSuffix?: T;
        priceLabel?: T;
        features?:
          | T
          | {
              text?: T;
              included?: T;
              id?: T;
            };
        ctaLabel?: T;
        id?: T;
      };
  industries?: T;
  needs?: T;
  companySizes?: T;
  relatedSolutions?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  pillar?: T;
  productGroup?: T;
  isFeatured?: T;
  order?: T;
  status?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  coverImage?: T;
  body?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  relatedSolutions?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  category?: T;
  publishedAt?: T;
  author?: T;
  status?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "policies_select".
 */
export interface PoliciesSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  coverImage?: T;
  body?: T;
  attachment?: T;
  sourceUrl?: T;
  relatedSolutions?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  documentType?: T;
  documentNumber?: T;
  issuingBody?: T;
  effectiveDate?: T;
  publishedAt?: T;
  status?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  company?: T;
  phone?: T;
  email?: T;
  type?: T;
  interestedSolutions?: T;
  companySize?: T;
  message?: T;
  preferredDate?: T;
  timeSlot?: T;
  consent?: T;
  leadStatus?: T;
  assignedTo?: T;
  source?: T;
  internalNotes?:
    | T
    | {
        note?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  phone?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Logo hiển thị ở góc trái header. Khuyến nghị PNG nền trong suốt, cao ~80px. Bỏ trống sẽ dùng logo chữ mặc định.
   */
  logo?: (number | null) | Media;
  departmentName?: string | null;
  hotline?: string | null;
  email?: string | null;
  address?: string | null;
  workingHours?: string | null;
  /**
   * Dùng link EMBED: Google Maps → Chia sẻ → "Nhúng bản đồ" → copy src (dạng https://www.google.com/maps/embed?pb=...). KHÔNG dùng link chia sẻ thường (sẽ bị chặn). Bỏ trống sẽ tự tạo bản đồ từ Địa chỉ.
   */
  mapEmbedUrl?: string | null;
  /**
   * Đường dẫn Zalo Official Account (vd: https://zalo.me/<oa_id>). Có giá trị sẽ hiện nút Zalo nổi ở góc dưới phải.
   */
  zaloOaUrl?: string | null;
  socials?:
    | {
        platform?: ('facebook' | 'zalo' | 'youtube' | 'linkedin' | 'tiktok') | null;
        url: string;
        id?: string | null;
      }[]
    | null;
  heroHeadline?: string | null;
  heroSubheadline?: string | null;
  heroPrimaryCtaLabel?: string | null;
  heroSecondaryCtaLabel?: string | null;
  heroImage?: (number | null) | Media;
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  footerNote?: string | null;
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  logo?: T;
  departmentName?: T;
  hotline?: T;
  email?: T;
  address?: T;
  workingHours?: T;
  mapEmbedUrl?: T;
  zaloOaUrl?: T;
  socials?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  heroHeadline?: T;
  heroSubheadline?: T;
  heroPrimaryCtaLabel?: T;
  heroSecondaryCtaLabel?: T;
  heroImage?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  footerNote?: T;
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}